version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./images.json:/app/images.json
    environment:
      - PYTHONUNBUFFERED=1