version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./images:/app/images
    environment:
      - PYTHONUNBUFFERED=1